const {chromium}=require('C:/Users/liuko/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const {spawn}=require('node:child_process');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'jev-final-'));const p=spawn('C:/Users/liuko/AppData/Local/Programs/Python/Python313/python.exe',[path.join(__dirname,'app.py'),'--port','8772','--db',path.join(tmp,'db.sqlite3')],{windowsHide:true,stdio:'pipe',cwd:__dirname});let browser;try{for(let i=0;i<50;i++){try{if((await fetch('http://127.0.0.1:8772/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,150));}browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errs=[];page.on('pageerror',e=>errs.push(e.message));page.on('console',m=>{if(m.type()==='error')errs.push(m.text())});await page.goto('http://127.0.0.1:8772');await page.waitForFunction(()=>!document.querySelector('#run').disabled);await page.click('#run');await page.waitForFunction(()=>document.querySelectorAll('.route-row').length===2&&!document.querySelector('#run').disabled);await page.click('#report');await page.waitForFunction(()=>document.querySelector('#report-dialog').open);assert.match(await page.locator('#report-body').innerText(),/不是正式尽调报告/);await page.click('[data-close="report-dialog"]');
await page.click('[data-view="integration-view"]');await page.click('#contract-preview');await page.waitForFunction(()=>document.querySelector('#contract-json').textContent.includes('bank_connected'));const h=JSON.parse(await page.locator('#contract-json').innerText());assert.equal(h.bank_connected,false);assert.equal(h.approval_decision,null);assert.equal(h.decision_results.length,2);const pending=page.waitForEvent('download');await page.click('#contract-export');const dl=await pending;await dl.saveAs(path.join(__dirname,'qa/final-handoff-example.json'));
await page.click('[data-view="development-view"]');await page.waitForFunction(()=>document.querySelectorAll('#dev-errors tbody tr').length===7);assert.match(await page.locator('#dev-results').innerText(),/17\/24/);assert.match(await page.locator('#dev-summary').innerText(),/尚未重新评测/);
await page.click('[data-view="ecosystem-view"]');assert.equal(await page.locator('.diagram-image').evaluate(e=>e.complete&&e.naturalWidth>0),true);
const checks=['six scenarios inherited regression','task trace uses actual selected run','summary boundary displayed','proposed JSON preserves null approval and bank_connected false','JSON download succeeds','development page loads 24-case source and seven errors','ecosystem vector loads'];
for(const size of [{width:1440,height:1100},{width:390,height:844}]){await page.setViewportSize(size);for(const view of ['workbench-view','ecosystem-view','development-view','integration-view']){await page.click('[data-view="'+view+'"]');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'horizontal overflow '+view);await page.screenshot({path:path.join(__dirname,'qa/final-'+view+'-'+size.width+'.png'),fullPage:true});}}
assert.deepEqual(errs,[]);checks.push('all four views fit desktop and mobile with no browser errors');await fs.writeFile(path.join(__dirname,'qa/final-product-results.json'),JSON.stringify({passed:true,checks,errors:errs,date:new Date().toISOString()},null,2));console.log(JSON.stringify({passed:true,checks,errors:errs}));}finally{if(browser)await browser.close();p.kill();await new Promise(r=>p.once('exit',r));await fs.rm(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});

